# Generated by Django 3.1.5 on 2021-01-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='target_ct',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='target_id',
            new_name='object_id',
        ),
    ]
