# Generated by Django 3.1.5 on 2021-01-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_auto_20210127_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='country',
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='continent',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='continent_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='country_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='postal_code',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='device',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loginhistory',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
