# Generated by Django 3.1.5 on 2021-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20210129_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmark_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
