# Generated by Django 3.1.5 on 2021-01-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_profile_bookmark_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bookmark_created',
        ),
    ]
