# Generated by Django 3.1.5 on 2021-01-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_remove_profile_bookmark_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='created',
            field=models.DateTimeField(verbose_name='Membership Created'),
        ),
    ]
